#!/bin/bash

# ================================
# Nanopore Visium RNA-seq data processing 
# Software: Percula v0.0.5, Space Ranger v4.0.1
#
# Purpose:
# Generate Space Ranger outputs, including spatial coordinates and image-aligned metadata,
# for downstream spatial transcriptomic analyses in Seurat
# ================================


conda activate percula

#Convert Nanopore FASTQ to short-read-compatible FASTQ files that can be handled by Space Ranger
#Note: only a small subset of FASTQ files is used, as gene expression quantification
# used for downstream analysis is performed using scNanoGPS, rather than Space Ranger.
fastcat --bam_out --threads 10 --recurse /data/nanopore/VISIUM_MEL13CM/fastq_pass/test.fastq.gz > test.bam
percula preprocess /home/spatial/MEL13ECM test.bam


# Run Space Ranger to obtain spatial metadata
# Note: --fastqs should point to the directory containing FASTQ files generated by Percula
spaceranger count --id=MEL13ECM \
--transcriptome=/home/spaceranger/refdata-gex-GRCh38-2024-A \
--image=/home/spaceranger/MEL13ECM/HE_NC1_MEL13ECM.tif \
--create-bam=false \
--slide=V14F20-298 \
--area=C1 \
--fastqs=/home/spatial/MEL13ECM


